//! HTTP 请求处理器（每个文件对应一组路由）

pub mod action;
pub mod bake;
pub mod captures;
pub mod config_checks;
pub mod creation;
pub mod debug;
pub mod diary;
pub mod health;
pub mod knowledge;
pub mod monitor;
pub mod pii;
pub mod preferences;
pub mod privacy;
pub mod profile;
pub mod query;
pub mod runtime;
pub mod snapshot;
pub mod tasks;
