//! HTTP 请求处理器（每个文件对应一组路由）

pub mod action;
pub mod bake;
pub mod capture_health;
pub mod captures;
pub mod config_checks;
pub mod creation;
pub mod creation_skill;
pub mod data;
pub mod debug;
pub mod diary;
pub mod health;
pub mod integration_skill;
pub mod knowledge;
pub mod monitor;
pub mod notification_channels;
pub mod pii;
pub mod preferences;
pub mod privacy;
pub mod profile;
pub mod query;
pub mod runtime;
pub mod snapshot;
pub mod tasks;
pub mod work_profile;
