import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { afterEach, describe, expect, it, vi } from 'vitest'
import PermissionPreparation from '../components/PermissionPreparation'
const row = { id: 'screen', name: '屏幕录制', description: '用于记录屏幕内容', status: 'required', message: '', optional: false }
const respond = (data: unknown, ok = true) => ({ ok, json: async () => data }) as Response
afterEach(() => { cleanup(); vi.restoreAllMocks(); vi.unstubAllGlobals() })
describe('简化的权限引导', () => {
  it('只提供开启操作，返回自动检查，已开启后移除按钮', async () => {
    const fetcher = vi.fn().mockResolvedValue(respond({ items: [row] }))
    vi.stubGlobal('fetch', fetcher)
    render(<PermissionPreparation />)
    expect(await screen.findByRole('button', { name: '去开启' })).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: /验证|检测/ })).not.toBeInTheDocument()
    fetcher.mockResolvedValue(respond({ items: [{ ...row, status: 'granted' }] }))
    fireEvent(window, new Event('focus'))
    expect(await screen.findByText('已开启')).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: '去开启' })).not.toBeInTheDocument()
    expect(fetcher.mock.calls.every(([, options]) => !options?.method)).toBe(true)
  })
  it('点击仅请求授权，不调用截图或验证接口', async () => {
    const fetcher = vi.fn(async (url: string) => respond(url.endsWith('/request') ? row : { items: [row] }))
    vi.stubGlobal('fetch', fetcher)
    render(<PermissionPreparation />)
    fireEvent.click(await screen.findByRole('button', { name: '去开启' }))
    await waitFor(() => expect(fetcher).toHaveBeenCalledWith(expect.stringContaining('/screen/request'), expect.objectContaining({ method: 'POST' })))
    expect(fetcher.mock.calls.some(([url]) => url.includes('/verify'))).toBe(false)
    expect(screen.queryByText('已开启')).not.toBeInTheDocument()
  })
  it('服务失败可重试', async () => {
    const fetcher = vi.fn().mockResolvedValue(respond({}, false))
    vi.stubGlobal('fetch', fetcher)
    render(<PermissionPreparation />)
    expect(await screen.findByRole('alert')).toBeInTheDocument()
    fetcher.mockResolvedValue(respond({ items: [row] }))
    fireEvent.click(screen.getByRole('button', { name: '重试' }))
    expect(await screen.findByText('屏幕录制')).toBeInTheDocument()
  })
  it('模拟初始化也读取真实权限，点击不会伪造已开启', async () => {
    const fetcher = vi.fn(async (url: string) => respond(url.endsWith('/request') ? row : { items: [row] }))
    vi.stubGlobal('fetch', fetcher)
    render(<PermissionPreparation sandbox />)
    fireEvent.click(await screen.findByRole('button', { name: '去开启' }))
    await waitFor(() => expect(fetcher).toHaveBeenCalledWith(expect.stringContaining('/request'), expect.anything()))
    expect(screen.queryByText('已开启')).not.toBeInTheDocument()
    expect(screen.getByText('更多可选设置').closest('details')).not.toHaveAttribute('open')
  })
  it('尚未轮到权限步骤时不检查、不弹窗', async () => {
    const fetcher = vi.fn().mockResolvedValue(respond({ items: [row] }))
    vi.stubGlobal('fetch', fetcher)
    render(<ul><PermissionPreparation variant="step" active={false} /></ul>)
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    expect(fetcher).not.toHaveBeenCalled()
    expect(screen.getByTestId('permission-stage')).toHaveClass('stage-item--pending')
  })
  it('步骤激活后已授权直接通过，不弹窗', async () => {
    const fetcher = vi.fn().mockResolvedValue(respond({ items: [{ ...row, status: 'granted' }] }))
    vi.stubGlobal('fetch', fetcher)
    const view = render(<ul><PermissionPreparation variant="step" active={false} /></ul>)
    view.rerender(<ul><PermissionPreparation variant="step" active /></ul>)
    const completed = await screen.findByRole('button', { name: '已完成' })
    expect(completed).toHaveClass('stage-status')
    expect(screen.queryByText('已自动检查通过')).not.toBeInTheDocument()
    expect(screen.getByTestId('permission-stage').querySelector('small')).toBeNull()
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    fireEvent.click(completed)
    expect(await screen.findByRole('dialog')).toBeInTheDocument()
  })
  it('缺权限自动弹窗，关闭后不打扰，可从步骤重新打开，授权后自动通过', async () => {
    const fetcher = vi.fn().mockResolvedValue(respond({ items: [row] }))
    vi.stubGlobal('fetch', fetcher)
    render(<ul><PermissionPreparation variant="step" active /></ul>)
    const modal = await screen.findByRole('dialog', { name: '开启采集权限' })
    expect(within(modal).getByText('屏幕录制')).toBeInTheDocument()
    fireEvent.click(within(modal).getByRole('button', { name: '关闭权限引导' }))
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    fireEvent(window, new Event('focus'))
    await waitFor(() => expect(fetcher.mock.calls.length).toBeGreaterThan(1))
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '去开启' }))
    expect(await screen.findByRole('dialog')).toBeInTheDocument()
    fetcher.mockResolvedValue(respond({ items: [{ ...row, status: 'granted' }] }))
    fireEvent(window, new Event('focus'))
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
    expect(screen.getByTestId('permission-stage')).toHaveClass('stage-item--succeeded')
  })
  it('弹窗支持 Escape 关闭，检查失败不误通过', async () => {
    vi.stubGlobal('fetch', vi.fn().mockResolvedValue(respond({}, false)))
    render(<ul><PermissionPreparation variant="step" active /></ul>)
    await screen.findByText('检查暂不可用')
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '去开启' }))
    await screen.findByRole('dialog')
    expect(screen.getByRole('alert')).toBeInTheDocument()
    fireEvent.keyDown(document, { key: 'Escape' })
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    expect(screen.getByTestId('permission-stage')).not.toHaveClass('stage-item--succeeded')
  })
  it('权限撤回后重新显示开启入口', async () => {
    const fetcher = vi.fn().mockResolvedValue(respond({ items: [{ ...row, status: 'granted' }] }))
    vi.stubGlobal('fetch', fetcher)
    render(<PermissionPreparation />)
    await screen.findByText('已开启')
    fetcher.mockResolvedValue(respond({ items: [row] }))
    fireEvent(window, new Event('focus'))
    expect(await screen.findByRole('button', { name: '去开启' })).toBeInTheDocument()
  })
})

describe('可选设置文案和浏览器操作', () => {
  it('移除重复说明与通知，仅在可选设置内展示提醒和操作反馈', async () => {
    const browser = { ...row, id: 'chrome', name: 'Google Chrome 网页增强', optional: true }
    const message = '尚未验证通过。请检查系统授权并打开有文字的应用窗口或普通网页，再次验证；若已开启仍无效，请退出并重新打开记忆面包。'
    browser.message = message
    vi.stubGlobal('fetch', vi.fn(async (url: string) => respond(url.endsWith('/request')
      ? { ...browser, message } : { items: [browser] })))
    render(<PermissionPreparation sandbox />)
    await screen.findByText('Google Chrome 网页增强')
    expect(screen.queryByText('完成通知')).not.toBeInTheDocument()
    expect(screen.queryByText('点击前往系统设置，开启后回到这里即可自动检查。')).not.toBeInTheDocument()
    expect(screen.queryByText(/这里检查本机实际权限/)).not.toBeInTheDocument()
    const optional = screen.getByText('更多可选设置').closest('details')!
    expect(within(optional).getByText('可以稍后在设置中继续开启，不影响咨询与创作。')).toBeInTheDocument()
    fireEvent.click(screen.getByText('更多可选设置'))
    optional.setAttribute('open', '')
    fireEvent.click(within(optional).getByRole('button', { name: '去开启' }))
    await waitFor(() => expect(within(optional).getByRole('button', { name: '去开启' })).toBeEnabled())
    expect(within(optional).getAllByText(message)).toHaveLength(1)
    expect(within(optional).getByText(message).closest('li')).not.toBeNull()
    expect(optional.querySelector('[role="status"]')).toBeNull()
  })
  it('浏览器开启后自动读取新状态并移除开启按钮', async () => {
    const browser = { ...row, id: 'safari', name: 'Safari 网页增强', optional: true }
    const fetcher = vi.fn().mockResolvedValue(respond({ items: [browser] }))
    vi.stubGlobal('fetch', fetcher)
    render(<PermissionPreparation />)
    await screen.findByText('Safari 网页增强')
    fetcher.mockResolvedValue(respond({ items: [{ ...browser, status: 'verified' }] }))
    fireEvent(window, new Event('focus'))
    expect(await screen.findByText('已开启')).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: '去开启' })).not.toBeInTheDocument()
  })
})
