-- Exact legacy-content match only. User edits and unrelated skills are preserved.
-- Content fingerprint (canonical JSON of the five matched fields): 5e82623c362f074a624d2f74fab1e876cc93b8c8b6e17b7d148c7af9f048051d
CREATE TABLE IF NOT EXISTS creation_skill_governance_backups (
    skill_id INTEGER NOT NULL,
    version TEXT NOT NULL,
    content_fingerprint TEXT NOT NULL,
    previous_summary TEXT NOT NULL,
    previous_description TEXT NOT NULL,
    previous_steps TEXT NOT NULL,
    previous_updated_at INTEGER NOT NULL,
    PRIMARY KEY (skill_id, version)
);
INSERT OR IGNORE INTO creation_skill_governance_backups
SELECT id, 'scope-v1', '5e82623c362f074a624d2f74fab1e876cc93b8c8b6e17b7d148c7af9f048051d', summary, skill_description, execution_steps, updated_at
FROM creation_skills WHERE client_skill_key = 'creation-skill-general-solution-review-doc' AND
    title = '技术架构方案评审文档模板' AND
    summary = '把目标、现状、约束、方案设计、关键取舍、实施路径和验收标准组织成可评审、可落地的方案文档。' AND
    skill_description = '{"purpose":"把目标、现状、约束、方案设计、关键取舍、实施路径和验收标准组织成可评审、可落地的方案文档。","document_types":["方案评审文档","技术方案","业务方案","流程设计方案"],"problems":["方案只有功能描述，缺少问题、约束和关键取舍","实施、验收、异常和回退路径不完整"],"domains":["产品设计","技术架构","流程优化","项目实施"],"deliverables":["包含设计图、关键取舍、实施验收和回退方案的评审文档"]}' AND
    execution_steps = '[{"id":"collect-solution-context","title":"收集需求与现状","objective":"用@记忆搜索 Tool 获取目标、用户问题、现有流程、历史方案、约束、已知风险和相关决策；明确目标与非目标。\n产出：需求、现状和约束清单","output":"","agents":[],"skills":[],"tools":["memory_search"],"retain_webpage_screenshot":true},{"id":"research-practices","title":"执行行业调研","objective":"需要外部标准、通行做法或技术选型时，用@互联网检索 Tool 和@GitHub 检索 Tool 获取一手资料与可比较案例。\n产出：外部实践和选型证据\n@行业调研 Agent","output":"","agents":["industry_research_agent"],"skills":[],"tools":["github_search","internet_search"],"retain_webpage_screenshot":true},{"id":"design-solution","title":"设计核心方案","objective":"围绕问题与约束设计结构、流程、接口或角色分工；用@Mermaid 画图 表达必要的架构、流程或时序。总体架构之后继续展开关键层级、独立组件或能力组，至少形成 3 个三级或四级子章节；每个子章节正文不少于 80 字，并说明职责边界、输入输出与依赖、关键机制或配置，以及指标、风险和回退。支撑组件可以按职责分组，不为图中每个节点机械建章。\n产出：方案设计与关键图示\n@方案设计 Agent","output":"","agents":["solution_design_agent"],"skills":[],"tools":["mermaid_diagram"],"retain_webpage_screenshot":true},{"id":"plan-delivery","title":"设计实施与验收","objective":"拆分阶段、依赖、责任、灰度、监控、验收和回退条件，识别需要评审者拍板的取舍。\n产出：实施计划、验收标准和风险表\n@方案设计 Agent","output":"","agents":["solution_design_agent"],"skills":[],"tools":[],"retain_webpage_screenshot":true},{"id":"draft-solution","title":"撰写方案文档","objective":"按摘要、背景目标、现状约束、方案、取舍、实施验收和风险回退完成全文。方案章节必须保留并充分展开关键层级、独立组件或能力组，至少形成 3 个三级或四级子章节；每个子章节正文不少于 80 字，并说明职责边界、输入输出与依赖、关键机制或配置，以及指标、风险和回退。\n产出：完整方案评审文档\n@文档撰写 Agent","output":"","agents":["document_writer_agent"],"skills":[],"tools":[],"retain_webpage_screenshot":true},{"id":"review-solution","title":"审校并交付","objective":"检查需求覆盖、设计一致性、图文对应、边界条件、实施可行性和验收可判断性；确认方案章节至少包含 3 个三级或四级子章节，每个子章节正文不少于 80 字，且内容对应真实组件或能力组，不用无关通用栏目凑数。\n产出：可进入评审的最终方案\n@质量审校 Agent","output":"","agents":["quality_review_agent"],"skills":[],"tools":[],"retain_webpage_screenshot":true}]';
UPDATE creation_skills SET summary = '用于技术架构设计与评审，明确系统边界、组件职责、接口依赖、容量与关键技术取舍，形成可实施、可验证的技术方案。',
    skill_description = '{"purpose":"用于技术架构设计与评审，明确系统边界、组件职责、接口依赖、容量与关键技术取舍，形成可实施、可验证的技术方案。","document_types":["技术架构设计文档","技术方案评审文档"],"problems":["技术方案缺少系统边界、组件接口与关键取舍","技术实施、容量验证与故障回退缺少可执行标准"],"domains":["软件架构","系统设计","技术实施"],"deliverables":["包含系统架构、组件接口、技术取舍、实施验证和故障回退的技术评审文档"],"applicability":{"version":1,"use_when":["用户的主交付物是系统技术架构设计或技术方案评审"],"not_for":["以招商、商家增长、营销运营或经营指标提升为主目标的业务方案；提及 AI 或视频模型作为手段不改变此边界"],"required_inputs":[],"output_structure":["技术背景与目标","系统边界与约束","架构与关键设计","技术取舍","实施验证与风险回退"]}}',
    execution_steps = '[{"id":"collect-solution-context","title":"收集需求与现状","objective":"用@记忆搜索 Tool 获取目标、用户问题、现有流程、历史方案、约束、已知风险和相关决策；明确目标与非目标。\n产出：需求、现状和约束清单","output":"","agents":[],"skills":[],"tools":["memory_search"],"retain_webpage_screenshot":true,"output_role":"process"},{"id":"research-practices","title":"执行行业调研","objective":"需要外部标准、通行做法或技术选型时，用@互联网检索 Tool 和@GitHub 检索 Tool 获取一手资料与可比较案例。\n产出：外部实践和选型证据\n@行业调研 Agent","output":"","agents":["industry_research_agent"],"skills":[],"tools":["github_search","internet_search"],"retain_webpage_screenshot":true,"output_role":"process"},{"id":"design-solution","title":"设计核心方案","objective":"围绕问题与约束设计结构、流程、接口或角色分工；用@Mermaid 画图 表达必要的架构、流程或时序。总体架构之后继续展开关键层级、独立组件或能力组，至少形成 3 个三级或四级子章节；每个子章节正文不少于 80 字，并说明职责边界、输入输出与依赖、关键机制或配置，以及指标、风险和回退。支撑组件可以按职责分组，不为图中每个节点机械建章。\n产出：方案设计与关键图示\n@方案设计 Agent","output":"","agents":["solution_design_agent"],"skills":[],"tools":["mermaid_diagram"],"retain_webpage_screenshot":true,"output_role":"process"},{"id":"plan-delivery","title":"设计实施与验收","objective":"拆分阶段、依赖、责任、灰度、监控、验收和回退条件，识别需要评审者拍板的取舍。\n产出：实施计划、验收标准和风险表\n@方案设计 Agent","output":"","agents":["solution_design_agent"],"skills":[],"tools":[],"retain_webpage_screenshot":true,"output_role":"process"},{"id":"draft-solution","title":"撰写方案文档","objective":"按摘要、背景目标、现状约束、方案、取舍、实施验收和风险回退完成全文。方案章节必须保留并充分展开关键层级、独立组件或能力组，至少形成 3 个三级或四级子章节；每个子章节正文不少于 80 字，并说明职责边界、输入输出与依赖、关键机制或配置，以及指标、风险和回退。\n产出：完整方案评审文档\n@文档撰写 Agent","output":"","agents":["document_writer_agent"],"skills":[],"tools":[],"retain_webpage_screenshot":true,"output_role":"document"},{"id":"review-solution","title":"审校并交付","objective":"检查需求覆盖、设计一致性、图文对应、边界条件、实施可行性和验收可判断性；确认方案章节至少包含 3 个三级或四级子章节，每个子章节正文不少于 80 字，且内容对应真实组件或能力组，不用无关通用栏目凑数。\n产出：可进入评审的最终方案\n@质量审校 Agent","output":"","agents":["quality_review_agent"],"skills":[],"tools":[],"retain_webpage_screenshot":true,"output_role":"process"}]',
    updated_at = CAST(strftime('%s','now') AS INTEGER) * 1000
WHERE client_skill_key = 'creation-skill-general-solution-review-doc' AND
    title = '技术架构方案评审文档模板' AND
    summary = '把目标、现状、约束、方案设计、关键取舍、实施路径和验收标准组织成可评审、可落地的方案文档。' AND
    skill_description = '{"purpose":"把目标、现状、约束、方案设计、关键取舍、实施路径和验收标准组织成可评审、可落地的方案文档。","document_types":["方案评审文档","技术方案","业务方案","流程设计方案"],"problems":["方案只有功能描述，缺少问题、约束和关键取舍","实施、验收、异常和回退路径不完整"],"domains":["产品设计","技术架构","流程优化","项目实施"],"deliverables":["包含设计图、关键取舍、实施验收和回退方案的评审文档"]}' AND
    execution_steps = '[{"id":"collect-solution-context","title":"收集需求与现状","objective":"用@记忆搜索 Tool 获取目标、用户问题、现有流程、历史方案、约束、已知风险和相关决策；明确目标与非目标。\n产出：需求、现状和约束清单","output":"","agents":[],"skills":[],"tools":["memory_search"],"retain_webpage_screenshot":true},{"id":"research-practices","title":"执行行业调研","objective":"需要外部标准、通行做法或技术选型时，用@互联网检索 Tool 和@GitHub 检索 Tool 获取一手资料与可比较案例。\n产出：外部实践和选型证据\n@行业调研 Agent","output":"","agents":["industry_research_agent"],"skills":[],"tools":["github_search","internet_search"],"retain_webpage_screenshot":true},{"id":"design-solution","title":"设计核心方案","objective":"围绕问题与约束设计结构、流程、接口或角色分工；用@Mermaid 画图 表达必要的架构、流程或时序。总体架构之后继续展开关键层级、独立组件或能力组，至少形成 3 个三级或四级子章节；每个子章节正文不少于 80 字，并说明职责边界、输入输出与依赖、关键机制或配置，以及指标、风险和回退。支撑组件可以按职责分组，不为图中每个节点机械建章。\n产出：方案设计与关键图示\n@方案设计 Agent","output":"","agents":["solution_design_agent"],"skills":[],"tools":["mermaid_diagram"],"retain_webpage_screenshot":true},{"id":"plan-delivery","title":"设计实施与验收","objective":"拆分阶段、依赖、责任、灰度、监控、验收和回退条件，识别需要评审者拍板的取舍。\n产出：实施计划、验收标准和风险表\n@方案设计 Agent","output":"","agents":["solution_design_agent"],"skills":[],"tools":[],"retain_webpage_screenshot":true},{"id":"draft-solution","title":"撰写方案文档","objective":"按摘要、背景目标、现状约束、方案、取舍、实施验收和风险回退完成全文。方案章节必须保留并充分展开关键层级、独立组件或能力组，至少形成 3 个三级或四级子章节；每个子章节正文不少于 80 字，并说明职责边界、输入输出与依赖、关键机制或配置，以及指标、风险和回退。\n产出：完整方案评审文档\n@文档撰写 Agent","output":"","agents":["document_writer_agent"],"skills":[],"tools":[],"retain_webpage_screenshot":true},{"id":"review-solution","title":"审校并交付","objective":"检查需求覆盖、设计一致性、图文对应、边界条件、实施可行性和验收可判断性；确认方案章节至少包含 3 个三级或四级子章节，每个子章节正文不少于 80 字，且内容对应真实组件或能力组，不用无关通用栏目凑数。\n产出：可进入评审的最终方案\n@质量审校 Agent","output":"","agents":["quality_review_agent"],"skills":[],"tools":[],"retain_webpage_screenshot":true}]';
